In [2]:
import pandas as pd
import numpy as np
import pickle

In [5]:
boston = pickle.load(open('E:/Machine Learning Course/Course2/week2/boston_housing_clean.pickle','rb'))
boston_data = boston['dataframe']
boston_description = boston['description']

In [6]:
boston_data.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  MEDV  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     17.8  392.83   4.03  34.7  
3     18.7  394.63   2.94  33.4  
4     18.7  396.90   5.33  36.2

In [9]:
print(boston_description)

Boston House Prices dataset

Notes
------
Data Set Characteristics:  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive
    
    :Median Value (attribute 14) is usually the target

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pupil-teacher ratio by town
      

In [10]:
y_col = 'MEDV'

X = boston_data.drop(y_col,axis=1)
y = boston_data[y_col]

In [11]:
from sklearn.preprocessing import StandardScaler
s = StandardScaler()
X_ss = s.fit_transform(X)

In [14]:
X2 = np.array(X)
man_trans = (X2-X2.mean(axis=0))/X2.std(axis=0)
np.allclose(X_ss,man_trans)

True

In [15]:
from sklearn.linear_model import LinearRegression

X = boston_data.drop(y_col,axis=1)
y = boston_data[y_col]

In [16]:
lr = LinearRegression()
lr.fit(X,y)

LinearRegression()

In [17]:
print(lr.coef_)

[-1.07170557e-01  4.63952195e-02  2.08602395e-02  2.68856140e+00
 -1.77957587e+01  3.80475246e+00  7.51061703e-04 -1.47575880e+00
  3.05655038e-01 -1.23293463e-02 -9.53463555e-01  9.39251272e-03
 -5.25466633e-01]


In [20]:
from sklearn.preprocessing import StandardScaler

s = StandardScaler()
X_ss = s.fit_transform(X)

In [21]:
lr2 = LinearRegression()
lr2.fit(X_ss,y)

LinearRegression()

In [22]:
print(lr2.coef_)

[-0.92041113  1.08098058  0.14296712  0.68220346 -2.06009246  2.67064141
  0.02112063 -3.10444805  2.65878654 -2.07589814 -2.06215593  0.85664044
 -3.74867982]


In [24]:
pd.DataFrame(zip(X.columns,lr2.coef_)).sort_values(by=1)

0         1
12    LSTAT -3.748680
7       DIS -3.104448
9       TAX -2.075898
10  PTRATIO -2.062156
4       NOX -2.060092
0      CRIM -0.920411
6       AGE  0.021121
2     INDUS  0.142967
3      CHAS  0.682203
11        B  0.856640
1        ZN  1.080981
8       RAD  2.658787
5        RM  2.670641

In [25]:
from sklearn.linear_model import Lasso
from sklearn.preprocessing import PolynomialFeatures

pf = PolynomialFeatures(degree=2,include_bias=False,)
X_pf = pf.fit_transform(X)

In [26]:
X_pf_ss = s.fit_transform(X_pf)

In [27]:
las = Lasso()
las.fit(X_pf_ss,y)
las.coef_

array([-0.        ,  0.        , -0.        ,  0.        , -0.        ,
        0.        , -0.        , -0.        , -0.        , -0.        ,
       -0.99073506,  0.        , -0.        , -0.        ,  0.        ,
       -0.        ,  0.06751971, -0.        , -0.        , -0.        ,
       -0.        , -0.        , -0.        , -0.        , -0.        ,
       -0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        , -0.        ,  0.        ,
       -0.        , -0.        , -0.        , -0.05012402, -0.        ,
       -0.        , -0.        , -0.        , -0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        , -0.        ,
       -0.        , -0.        , -0.        , -0.        , -0.        ,
       -0.        ,  0.        , -0.        ,  3.30027884, -0.  

In [33]:
las1 = Lasso(alpha=0.1)
las1.fit(X_pf_ss,y)
print('sum of coefficient ',abs(las1.coef_).sum())
print('sum of coefficient that not equal to zero ',(las1.coef_ != 0).sum())

sum of coefficient  26.172415115426787
sum of coefficient that not equal to zero  23


In [34]:
las2 = Lasso(alpha=1)
las2.fit(X_pf_ss,y)
print('sum of coefficient ',abs(las2.coef_).sum())
print('sum of coefficient that not equal to zero ',(las2.coef_ != 0).sum())

sum of coefficient  8.472405227760156
sum of coefficient that not equal to zero  7


In [41]:
from sklearn.metrics import r2_score
r2_score(y,las2.predict(X_pf_ss))

0.7207000461229027

In [37]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X_pf,y,test_size=0.3,random_state=72018)

In [43]:
X_train_s = s.fit_transform(X_train)
las.fit(X_train_s,y_train)
X_test_s = s.transform(X_test)
y_pred = las.predict(X_test_s)
r2_score(y_pred,y_test)

0.3318289609088583

In [44]:
X_train_s = s.fit_transform(X_train)
las1.fit(X_train_s,y_train)
X_test_s = s.transform(X_test)
y_pred = las1.predict(X_test_s)
r2_score(y_pred,y_test)

0.711227316581263

In [46]:
las001 = Lasso(alpha=0.001,max_iter=100000)
X_train_s = s.fit_transform(X_train)
las001.fit(X_train_s,y_train)
X_test_s = s.transform(X_test)
y_pred = las001.predict(X_test_s)
print('r2_score  for alpha=0.001',r2_score(y_pred,y_test))


lr = LinearRegression()
lr.fit(X_train_s,y_train)
y_pred_lr = lr.predict(X_test_s)
print('r2_score  for alpha=0.001',r2_score(y_pred_lr,y_test))


print('sum of coefficient ',abs(las001.coef_).sum())
print('sum of coefficient that not equal to zero ',(las001.coef_!= 0).sum())
print('sum of coefficient ',abs(lr.coef_).sum())
print('sum of coefficient that not equal to zero ',(lr.coef_!= 0).sum())

r2_score  for alpha=0.001 0.8688370609866953
r2_score  for alpha=0.001 0.8558518908813447
sum of coefficient  435.57232290440345
sum of coefficient that not equal to zero  90
sum of coefficient  1183.891813866429
sum of coefficient that not equal to zero  104


In [47]:
from sklearn.linear_model import Ridge

In [48]:
r = Ridge(alpha=0.001)
X_train_s = s.fit_transform(X_train)
r.fit(X_train_s,y_train)
X_test_s = s.transform(X_test)
y_pred_r = r.predict(X_test_s)
r.coef_

array([  7.69158031,   9.88890473, -25.00525751,   5.31046818,
        -2.60993701,  14.95803313,  22.31375473, -22.8579177 ,
        27.76499232,  -1.5651209 ,  17.07749893,  21.85840549,
        11.57430607,   1.0501267 ,   0.43058525,  13.78571186,
         1.8138621 ,  -8.34497303,   4.99428114,  -3.56428247,
        -3.43620979, -16.33550823,  -7.04652168,   6.60858547,
        -1.47661   ,   4.68585754,  -1.30404236,  -0.05944784,
        -0.30379373, -12.84226172,   1.97669112,   1.08130677,
        -0.67550448,  -1.07931934,   4.49162494,  -4.26689794,
         4.67486611,  -1.28089201,   8.66602804,  -0.27373083,
        -8.11960573,  11.78297941,   6.53845776,   1.32299881,
         2.05956326,   0.89895643,   1.7894665 ,   4.74421976,
        -4.66441531,   5.31046818,  -3.23646667,  -8.66803392,
         0.97293208,   1.13586914,   0.29037187,  -1.63142731,
        -2.92599804,   2.92315095,  -0.73510358,  11.89603615,
         0.75403388,  -7.53119729,  18.30567198, -22.16

In [49]:
las001.coef_

array([ 0.00000000e+00,  0.00000000e+00, -1.70077961e+01,  2.59218903e+00,
        0.00000000e+00,  1.34310751e+01,  1.00617885e+01, -1.95420304e+01,
        9.23745604e+00,  0.00000000e+00,  6.15850148e+00,  1.70865644e+01,
        1.14862999e+01,  1.20761498e+00,  2.19212098e-01,  1.08266235e+01,
        2.18532977e+00, -7.10563499e+00,  4.31223434e+00, -1.52608936e+00,
       -2.09150369e+00, -9.66889138e+00,  0.00000000e+00,  0.00000000e+00,
       -1.17685620e+00,  3.86518537e+00,  3.77856352e-01,  1.94047899e-01,
       -2.95878630e-01, -3.47818534e+00,  2.91171870e-01,  7.20249225e-01,
       -7.95193179e-01, -7.39638413e-01,  2.40656329e+00, -8.91898909e-01,
        2.83533285e+00, -9.83613898e-01,  3.86402286e+00, -9.62972947e-01,
        6.91383535e+00,  6.19985710e+00,  4.19727921e+00,  8.92131589e-01,
        2.02792608e+00,  2.60830224e+00, -3.97491024e+00,  2.57367502e+00,
       -4.56754935e+00,  2.08634607e+00, -2.00046119e+00, -7.41198425e+00,
        1.60411709e+00,  

In [50]:
print('sum of coefficient of r',abs(r.coef_).sum())
print('sum of coefficient of lasso',abs(las001.coef_).sum())

print('sum of coefficient that not equal to zero of r',(r.coef_ != 0).sum())
print('sum of coefficient that not equal to zero of lasso',(las001.coef_ != 0).sum())

sum of coefficient of r 792.8673755130682
sum of coefficient of lasso 435.57232290440345
sum of coefficient that not equal to zero of r 104
sum of coefficient that not equal to zero of lasso 90
